---
- name: VTEX | Check Yarn
  shell: which yarn
  register: yarn_installed
  failed_when: false
  changed_when: false
  ignore_errors: true
  check_mode: false

- name: VTEX | Yarn installed
  debug:
    verbosity: 1
    msg: "Yarn is installed? {{ yarn_installed.rc == 0  }}"

- name: VTEX | Install Yarn
  when: yarn_installed.rc != 0
  ansible.builtin.shell: "{{ yarn_install_command }}"
  changed_when: true

- name: VTEX | Check VTEX
  shell: which vtex
  register: vtex_installed
  failed_when: false
  changed_when: false
  ignore_errors: true
  check_mode: false

- name: VTEX | VTEX installed
  debug:
    verbosity: 1
    msg: "VTEX is installed? {{ vtex_installed.rc == 0  }}"

- name: VTEX | Install VTEX CLI
  become: true
  when: vtex_installed.rc != 0
  ansible.builtin.shell: "{{ vtex_installation_command }}"
  changed_when: true

- name: VTEX | Install VTEX Plugins
  when: vtex_installed.rc != 0
  ansible.builtin.shell: "{{ vtex_logs_install_command }}"
  changed_when: true

- name: VTEX | Add VTEX symlink
  become: true
  file:
    src: "{{ volta_bin_path }}/node"
    dest: /usr/local/bin/node
    owner: host_user
    group: host_user
    state: link
