---
- name: Node | Check Yarn
  shell: which yarn
  register: yarn_installed
  failed_when: false
  changed_when: false
  ignore_errors: true
  check_mode: false

- name: Node | Yarn installed
  debug:
    verbosity: 1
    msg: "Yarn is installed? {{ yarn_installed.rc == 0  }}"

- name: Node | Install Yarn
  when: yarn_installed.rc != 0
  ansible.builtin.shell: "{{ yarn_install_command }}"
  changed_when: true

- name: Node | Check VTEX
  shell: which vtex
  register: vtex_installed
  failed_when: false
  changed_when: false
  ignore_errors: true
  check_mode: false

- name: Node | VTEX installed
  debug:
    verbosity: 1
    msg: "VTEX is installed? {{ vtex_installed.rc == 0  }}"

- name: Node | Install VTEX CLI
  become: true
  when: vtex_installed.rc != 0
  ansible.builtin.shell: "{{ vtex_installation_command }}"
  changed_when: true

- name: Node | Install VTEX Plugins
  when: vtex_installed.rc != 0
  ansible.builtin.shell: "{{ vtex_logs_install_command }}"
  changed_when: true
