---
- name: Pass | Ensure folder is created
  ansible.builtin.file:
    dest: "{{ pass_dest_folder }}"
    state: directory

- name: Pass | Install private key
  ansible.builtin.copy:
    content: "{{ git_user_signing_id }}"
    dest: "{{ pass_id_dest }}"
    mode: "{{ pass_id_permissions }}"