---
- name: Dotfiles | Stow | Ensure is installed
  become: true
  ansible.builtin.apt:
    name: stow
    state: present

- name: Dotfiles | Stow | Search modules
  ansible.builtin.find:
    paths: "{{ stow_folder_path }}"
    recurse: false
    file_type: directory
  register: found_modules

- name: Dotfiles | Stow | Found modules 
  debug:
    verbosity: 1
    msg: "Modules => {{ found_modules.files }}"

- name: Dotfiles | Stow | Deploy modules
  with_items: '{{ found_modules.files }}'
  stow:
    state: supress
    dir: "{{ stow_folder_path }}"
    package: '{{ item.path.split("/")[-1] }}'