---
# SSH Vars
ssh_private_key_name: "id_rsa"
ssh_public_key_name: "{{ ssh_private_key_name }}.pub"

ssh_dest_folder: "{{ ansible_user_dir }}/.ssh"
ssh_folder_permissions: "0700"

ssh_orig_private_key_path: "{{ ssh_private_key_name }}"
ssh_dest_private_key_path: "{{ ssh_dest_folder }}/{{ ssh_private_key_name }}"
ssh_private_key_permissions: "0600"

ssh_orig_public_key_path: "{{ ssh_public_key_name }}"
ssh_dest_public_key_path: "{{ ssh_dest_folder }}/{{ ssh_public_key_name }}"
ssh_public_key_permissions: "0644"