- name: "SSH | Copy SSH keys"
  copy:
    dest: "{{ ansible_user_dir }}/.ssh/{{ ssh_key_item.key }}"
    content: "{{ ssh_key_item.value }}"
    mode: "0600"
  loop_control:
    loop_var: ssh_key_item
  with_items: "{{ ssh_keys | default({}) | dict2items }}"