---
# vars file for node
volta_download_url: https://get.volta.sh
volta_download_path: "{{ tmp_dir }}/volta-setup.sh"
volta_download_permissions: "0755"
volta_installation_path: "{{ home_dir }}/.volta"
volta_bin_path: "{{ volta_installation_path }}/bin"

bun_setup_url: curl -fsSL https://bun.sh/install | bash

node_install_command: "{{ volta_bin_path }}/volta install node"
yarn_install_command: "{{ volta_bin_path }}/volta install yarn"

vtex_installation_command: "curl -L https://vtex.io/vtexcli/install | sh"
vtex_logs_install_command: "vtex plugins add logs"
