- name: Chrome | Download
  get_url:
    url: "{{ chrome_download_url }}"
    dest: "{{ chrome_donwload_path }}"
  become: true

- name: Chrome | Install
  become: true
  apt:
    deb: "{{ chrome_donwload_path }}"
