---
- name: Volta | Debian install
  ansible.builtin.import_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- name: Node | Install Node
  when: true
  ansible.builtin.shell: "{{ node_install_command }}"
  changed_when: true

- name: Node | Install Bun
  when: true
  become: true
  ansible.builtin.shell:
    cmd: "set -o pipefail && {{ bun_setup_url }}"
    executable: /bin/bash
  changed_when: true

- name: Node | Install Yarn
  when: true
  ansible.builtin.shell: "{{ yarn_install_command }}"
  changed_when: true

- name: Node | Install VTEX CLI
  become: true
  when: true
  ansible.builtin.shell: "{{ vtex_installation_command }}"
  changed_when: true

- name: Node | Install VTEX Plugins
  when: true
  ansible.builtin.shell: "{{ vtex_logs_install_command }}"
  changed_when: true
